INSERT INTO districts (district_name, province_id) VALUES
-- Adana
('Seyhan', 1),
('Yüreğir', 1),
('Çukurova', 1),
('Karaisalı', 1),
('Karataş', 1),
('Pozantı', 1),
('Aladağ', 1),
('Feke', 1),
('Saimbeyli', 1),
('Sarıçam', 1),
('Tufanbeyli', 1),
('Yumurtalık', 1),
('Yumurtalık', 1),

-- Adıyaman
('Adıyaman Merkez', 2),
('Besni', 2),
('Çelikhan', 2),
('Gerger', 2),
('Gölbaşı', 2),
('Kahta', 2),
('Samsat', 2),
('Sincik', 2),
('Tut', 2),

-- Afyonkarahisar
('Afyonkarahisar Merkez', 3),
('Başmakçı', 3),
('Bayat', 3),
('Bolvadin', 3),
('Çay', 3),
('Çobanlar', 3),
('Dazkırı', 3),
('Dinar', 3),
('Emirdağ', 3),
('Evciler', 3),
('Hocalar', 3),
('İhsaniye', 3),
('İscehisar', 3),
('Kızılören', 3),
('Sandıklı', 3),
('Sinanpaşa', 3),
('Sultandağı', 3),
('Şuhut', 3),

-- Ağrı
('Ağrı Merkez', 4),
('Diyadin', 4),
('Doğubayazıt', 4),
('Eleşkirt', 4),
('Hamur', 4),
('Patnos', 4),
('Taşlıçay', 4),
('Tutak', 4),

-- Amasya
('Amasya Merkez', 5),
('Göynücek', 5),
('Gümüşhacıköy', 5),
('Hamamözü', 5),
('Merzifon', 5),
('Suluova', 5),
('Taşova', 5),

-- Ankara
('Akyurt', 6),
('Altındağ', 6),
('Ayaş', 6),
('Bala', 6),
('Beypazarı', 6),
('Çamlıdere', 6),
('Çankaya', 6),
('Çubuk', 6),
('Elmadağ', 6),
('Etimesgut', 6),
('Evren', 6),
('Gölbaşı', 6),
('Güdül', 6),
('Haymana', 6),
('Kalecik', 6),
('Kazan', 6),
('Keçiören', 6),
('Kızılcahamam', 6),
('Mamak', 6),
('Nallıhan', 6),
('Polatlı', 6),
('Pursaklar', 6),
('Sincan', 6),
('Şereflikoçhisar', 6),
('Yenimahalle', 6),

-- Antalya
('Akseki', 7),
('Aksu', 7),
('Alanya', 7),
('Demre', 7),
('Döşemealtı', 7),
('Elmalı', 7),
('Finike', 7),
('Gazipaşa', 7),
('Gündoğmuş', 7),
('İbradi', 7),
('Kale', 7),
('Kaş', 7),
('Kemer', 7),
('Kepez', 7),
('Konyaaltı', 7),
('Korkuteli', 7),
('Kumluca', 7),
('Manavgat', 7),
('Muratpaşa', 7),
('Serik', 7),

-- Artvin
('Ardanuç', 8),
('Arhavi', 8),
('Artvin Merkez', 8),
('Borçka', 8),
('Hopa', 8),
('Murgul', 8),
('Şavşat', 8),
('Yusufeli', 8),

-- Aydın
('Bozdoğan', 9),
('Buharkent', 9),
('Çine', 9),
('Didim', 9),
('Efeler', 9),
('Germencik', 9),
('İncirliova', 9),
('Karacasu', 9),
('Karpuzlu', 9),
('Koçarlı', 9),
('Köşk', 9),
('Kuşadası', 9),
('Kuyucak', 9),
('Nazilli', 9),
('Söke', 9),
('Sultanhisar', 9),
('Yenipazar', 9),

-- Balıkesir
('Altıeylül', 10),
('Ayvalık', 10),
('Balya', 10),
('Bandırma', 10),
('Bigadiç', 10),
('Burhaniye', 10),
('Dursunbey', 10),
('Edremit', 10),
('Erdek', 10),
('Gömeç', 10),
('Gönen', 10),
('Havran', 10),
('İvrindi', 10),
('Karesi', 10),
('Kepsut', 10),
('Manyas', 10),
('Marmara', 10),
('Savaştepe', 10),
('Sındırgı', 10),
('Susurluk', 10),

-- Bilecik
('Bilecik Merkez', 11),
('Bozüyük', 11),
('Gölpazarı', 11),
('İnhisar', 11),
('Osmaneli', 11),
('Pazaryeri', 11),
('Söğüt', 11),
('Yenipazar', 11),

-- Bingöl
('Bingöl Merkez', 12),
('Genç', 12),
('Karlıova', 12),
('Kiğı', 12),
('Solhan', 12),
('Yayladere', 12),
('Yedisu', 12),

-- Bitlis
('Adilcevaz', 13),
('Ahlat', 13),
('Bitlis Merkez', 13),
('Güroymak', 13),
('Hizan', 13),
('Mutki', 13),
('Tatvan', 13),

-- Bolu
('Bolu Merkez', 14),
('Dörtdivan', 14),
('Gerede', 14),
('Göynük', 14),
('Kıbrıscık', 14),
('Mengen', 14),
('Mudurnu', 14),
('Seben', 14),
('Yeniçağa', 14),

-- Burdur
('Ağlasun', 15),
('Altınyayla', 15),
('Bucak', 15),
('Burdur Merkez', 15),
('Çavdır', 15),
('Çeltikçi', 15),
('Gölhisar', 15),
('Karamanlı', 15),
('Kemer', 15),
('Tefenni', 15),
('Yeşilova', 15),

-- Bursa
('Büyükorhan', 16),
('Gemlik', 16),
('Gürsu', 16),
('Harmancık', 16),
('İnegöl', 16),
('İznik', 16),
('Karacabey', 16),
('Keles', 16),
('Kestel', 16),
('Mudanya', 16),
('Mustafakemalpaşa', 16),
('Nilüfer', 16),
('Orhaneli', 16),
('Orhangazi', 16),
('Osmangazi', 16),
('Yenişehir', 16),
('Yıldırım', 16),

-- Çanakkale
('Ayvacık', 17),
('Bayramiç', 17),
('Biga', 17),
('Bozcaada', 17),
('Çan', 17),
('Çanakkale Merkez', 17),
('Eceabat', 17),
('Ezine', 17),
('Gelibolu', 17),
('Gökçeada', 17),
('Lapseki', 17),
('Yenice', 17),

-- Çankırı
('Atkaracalar', 18),
('Bayramören', 18),
('Çankırı Merkez', 18),
('Çerkeş', 18),
('Eldivan', 18),
('Ilgaz', 18),
('Kızılırmak', 18),
('Korgun', 18),
('Kurşunlu', 18),
('Orta', 18),
('Şabanözü', 18),
('Yapraklı', 18),

-- Çorum
('Alaca', 19),
('Bayat', 19),
('Boğazkale', 19),
('Çorum Merkez', 19),
('Dodurga', 19),
('İskilip', 19),
('Kargı', 19),
('Laçin', 19),
('Mecitözü', 19),
('Oğuzlar', 19),
('Ortaköy', 19),
('Osmancık', 19),
('Sungurlu', 19),
('Uğurludağ', 19),

-- Denizli
('Acıpayam', 20),
('Babadağ', 20),
('Baklan', 20),
('Bekilli', 20),
('Beyağaç', 20),
('Bozkurt', 20),
('Buldan', 20),
('Çal', 20),
('Çameli', 20),
('Çardak', 20),
('Çivril', 20),
('Denizli Merkez', 20),
('Güney', 20),
('Honaz', 20),
('Kale', 20),
('Sarayköy', 20),
('Serinhisar', 20),
('Tavas', 20),

-- Diyarbakır
('Bağlar', 21),
('Bismil', 21),
('Çermik', 21),
('Çınar', 21),
('Çüngüş', 21),
('Dicle', 21),
('Eğil', 21),
('Ergani', 21),
('Hani', 21),
('Hazro', 21),
('Kayapınar', 21),
('Kocaköy', 21),
('Kulp', 21),
('Lice', 21),
('Silvan', 21),

-- Edirne
('Edirne Merkez', 22),
('Enez', 22),
('Havsa', 22),
('İpsala', 22),
('Keşan', 22),
('Lalapaşa', 22),
('Meriç', 22),
('Süloğlu', 22),
('Uzunköprü', 22),

-- Elazığ
('Ağın', 23),
('Alacakaya', 23),
('Arıcak', 23),
('Baskil', 23),
('Elazığ Merkez', 23),
('Karakoçan', 23),
('Keban', 23),
('Kovancılar', 23),
('Maden', 23),
('Palu', 23),
('Sivrice', 23),

-- Erzincan
('Erzincan Merkez', 24),
('Çayırlı', 24),
('İliç', 24),
('Kemaliye', 24),
('Otlukbeli', 24),
('Refahiye', 24),
('Tercan', 24),
('Üzümlü', 24),

-- Erzurum
('Erzurum Merkez', 25),
('Aziziye', 25),
('Çat', 25),
('Hınıs', 25),
('İspir', 25),
('Karaçoban', 25),
('Narman', 25),
('Oltu', 25),
('Olur', 25),
('Pasinler', 25),
('Palandöken', 25),
('Şenkaya', 25),
('Tekman', 25),
('Tortum', 25),
('Yakutiye', 25),

-- Eskişehir
('Eskişehir Merkez', 26),
('Aliikiz', 26),
('Beylikova', 26),
('Çifteler', 26),
('Günyüzü', 26),
('Han', 26),
('İnönü', 26),
('Mahmudiye', 26),
('Mihalıççık', 26),
('Odunpazarı', 26),
('Sarıcakaya', 26),
('Seyitgazi', 26),
('Sivrihisar', 26),

-- Gaziantep
('Gaziantep Merkez', 27),
('Araban', 27),
('Barak', 27),
('Birecik', 27),
('Karkamış', 27),
('Nizip', 27),
('Oğuzeli', 27),
('Şahinbey', 27),
('Şehitkamil', 27),
('Şehitkamil', 27),
('Yavuzeli', 27),

-- Giresun
('Giresun Merkez', 28),
('Alucra', 28),
('Bulancak', 28),
('Çamoluk', 28),
('Çanakçı', 28),
('Dereli', 28),
('Doğankent', 28),
('Espiye', 28),
('Eynesil', 28),
('Görele', 28),
('Keşap', 28),
('Piraziz', 28),
('Şebinkarahisar', 28),
('Tirebolu', 28),
('Yağlıdere', 28),

-- Gümüşhane
('Gümüşhane Merkez', 29),
('Kelkit', 29),
('Köse', 29),
('Şiran', 29),
('Torul', 29),

-- Hakkari
('Hakkari Merkez', 30),
('Çukurca', 30),
('Şemdinli', 30),
('Yüksekova', 30),

-- Hatay
('Hatay Merkez', 31),
('Altınözü', 31),
('Belen', 31),
('Defne', 31),
('Dörtyol', 31),
('Erzin', 31),
('Hassa', 31),
('İskenderun', 31),
('Kırıkhan', 31),
('Reyhanlı', 31),
('Samandağ', 31),
('Yayladağı', 31),

-- Iğdır
('Iğdır Merkez', 32),
('Aralık', 32),
('Karakoyunlu', 32),
('Tuzluca', 32),

-- Isparta
('Isparta Merkez', 33),
('Aksu', 33),
('Egirdir', 33),
('Gölcük', 33),
('Isparta Merkez', 33),
('Şarkikaraağaç', 33),
('Yalvaç', 33),
('Senirkent', 33),

-- İstanbul
('Adalar', 34),
('Ataşehir', 34),
('Avcılar', 34),
('Bakırköy', 34),
('Başakşehir', 34),
('Bayrampaşa', 34),
('Beşiktaş', 34),
('Beyoğlu', 34),
('Büyükçekmece', 34),
('Esenler', 34),
('Esenyurt', 34),
('Eyüpsultan', 34),
('Fatih', 34),
('Gaziosmanpaşa', 34),
('Kadıköy', 34),
('Kagithane', 34),
('Kartal', 34),
('Küçükçekmece', 34),
('Maltepe', 34),
('Pendik', 34),
('Sancaktepe', 34),
('Sarıyer', 34),
('Silivri', 34),
('Sultanbeyli', 34),
('Sultangazi', 34),
('Şişli', 34),
('Üsküdar', 34),
('Zeytinburnu', 34),

-- İzmir
('Aliağa', 35),
('Bergama', 35),
('Bayındır', 35),
('Bayraklı', 35),
('Buca', 35),
('Bornova', 35),
('Çeşme', 35),
('Çiğli', 35),
('Gaziemir', 35),
('Güzelbahçe', 35),
('Karşıyaka', 35),
('Kemalpaşa', 35),
('Kiraz', 35),
('Kınık', 35),
('Menemen', 35),
('Narlıdere', 35),
('Ödemiş', 35),
('Seferihisar', 35),
('Selçuk', 35),
('Tire', 35),
('Torbalı', 35),
('Urla', 35),

-- Kars
('Kars Merkez', 36),
('Ardahan', 36),
('Digor', 36),
('Sarıkamış', 36),
('Selim', 36),
('Susuz', 36),

-- Kastamonu
('Kastamonu Merkez', 37),
('Abana', 37),
('Araç', 37),
('Daday', 37),
('Devrekani', 37),
('Hanönü', 37),
('İhsangazi', 37),
('İnebolu', 37),
('Küre', 37),
('Pınarbaşı', 37),
('Seydiler', 37),
('Tosya', 37),

-- Kayseri
('Kayseri Merkez', 38),
('Akkışla', 38),
('Bünyan', 38),
('Develi', 38),
('Felahiye', 38),
('Hacılar', 38),
('İncesu', 38),
('Kocasinan', 38),
('Melikgazi', 38),
('Özvatan', 38),
('Pınarbaşı', 38),
('Sarıoğlan', 38),
('Sarıoğlan', 38),
('Talas', 38),
('Yeşilhisar', 38),

-- Kırklareli
('Kırklareli Merkez', 39),
('Babaeski', 39),
('Demirköy', 39),
('Kofçaz', 39),
('Lüleburgaz', 39),
('Pehlivanköy', 39),
('Pınarhisar', 39),
('Vize', 39),

-- Kırşehir
('Kırşehir Merkez', 40),
('Akçakent', 40),
('Akpınar', 40),
('Boztepe', 40),
('Çiçekdağı', 40),
('Kaman', 40),
('Mucur', 40),

-- Kocaeli
('Kocaeli Merkez', 41),
('Başiskele', 41),
('Çayırova', 41),
('Darıca', 41),
('Derince', 41),
('Dilovası', 41),
('Gebze', 41),
('Gölcük', 41),
('İzmit', 41),
('Kandıra', 41),
('Karamürsel', 41),
('Kartepe', 41),
('Körfez', 41),

-- Konya
('Akşehir', 42),
('Akören', 42),
('Beyşehir', 42),
('Bozkır', 42),
('Çeltik', 42),
('Çumra', 42),
('Derebucak', 42),
('Doğanhisar', 42),
('Ereğli', 42),
('Hadim', 42),
('Hüyük', 42),
('Karatay', 42),
('Kulu', 42),
('Meram', 42),
('Sarıveliler', 42),
('Selçuklu', 42),
('Seydişehir', 42),
('Yunak', 42),

-- Kütahya
('Kütahya Merkez', 43),
('Altıntaş', 43),
('Aslanapa', 43),
('Çavdarhisar', 43),
('Domaniç', 43),
('Dumlupınar', 43),
('Emet', 43),
('Gediz', 43),
('Hisarcık', 43),
('Pazarlar', 43),
('Şaphane', 43),
('Simav', 43),
('Tavşanlı', 43),

-- Malatya
('Malatya Merkez', 44),
('Akçadağ', 44),
('Arapgir', 44),
('Arguvan', 44),
('Battalgazi', 44),
('Darende', 44),
('Doğanşehir', 44),
('Doğanyol', 44),
('Hekimhan', 44),
('Kale', 44),
('Kuluncak', 44),
('Pütürge', 44),
('Yazıhan', 44),
('Yeşilyurt', 44),

-- Manisa
('Manisa Merkez', 45),
('Ahmetli', 45),
('Akhisar', 45),
('Alaşehir', 45),
('Demirci', 45),
('Gölmarmara', 45),
('Gördes', 45),
('Kırkağaç', 45),
('Köprübaşı', 45),
('Kula', 45),
('Salihli', 45),
('Sarıgöl', 45),
('Saruhanlı', 45),
('Selendi', 45),
('Soma', 45),

-- Kahramanmaraş
('Kahramanmaraş Merkez', 46),
('Afşin', 46),
('Andırın', 46),
('Çağlayancerit', 46),
('Dulkadiroğlu', 46),
('Ekinözü', 46),
('Elbistan', 46),
('Göksun', 46),
('Nurhak', 46),
('Pazarcık', 46),
('Türkoğlu', 46),

-- Mardin
('Mardin Merkez', 47),
('Dargeçit', 47),
('Derik', 47),
('Kızıltepe', 47),
('Mazıdağı', 47),
('Midyat', 47),
('Nusaybin', 47),
('Ömerli', 47),
('Savur', 47),
('Yeşilli', 47),

-- Muğla
('Muğla Merkez', 48),
('Bodrum', 48),
('Dalaman', 48),
('Datça', 48),
('Fethiye', 48),
('Kavaklıdere', 48),
('Köyceğiz', 48),
('Marmaris', 48),
('Menteşe', 48),
('Milas', 48),
('Ortaca', 48),
('Seydikemer', 48),
('Ula', 48),
('Yatağan', 48),

-- Muş
('Muş Merkez', 49),
('Bulanık', 49),
('Malazgirt', 49),
('Varto', 49),
('Korkut', 49),
('Hasköy', 49),

-- Nevşehir
('Nevşehir Merkez', 50),
('Acıgöl', 50),
('Avanos', 50),
('Derinkuyu', 50),
('Gülşehir', 50),
('Hacıbektaş', 50),
('Kozaklı', 50),
('Ürgüp', 50),

-- Niğde
('Niğde Merkez', 51),
('Altunhisar', 51),
('Bor', 51),
('Çamardı', 51),
('Çiftlik', 51),
('Ulukışla', 51),
('Kozaklı', 51),
('Ürgüp', 51),

-- Ordu
('Ordu Merkez', 52),
('Akkuş', 52),
('Altınordu', 52),
('Aybastı', 52),
('Çamaş', 52),
('Çatalpınar', 52),
('Çaybaşı', 52),
('Fatsa', 52),
('Gölköy', 52),
('Gülyalı', 52),
('Gürgentepe', 52),
('İkizce', 52),
('Kabadüz', 52),
('Kabataş', 52),
('Korgan', 52),
('Kumru', 52),
('Mesudiye', 52),
('Perşembe', 52),
('Ulubey', 52),

-- Rize
('Rize Merkez', 53),
('Ardeşen', 53),
('Çamlıhemşin', 53),
('Çayeli', 53),
('Fındıklı', 53),
('Güneysu', 53),
('Hemşin', 53),
('İkizdere', 53),
('İyidere', 53),
('Pazar', 53),

-- Sakarya
('Sakarya Merkez', 54),
('Adapazarı', 54),
('Akyazı', 54),
('Arifiye', 54),
('Erenler', 54),
('Ferizli', 54),
('Geyve', 54),
('Hendek', 54),
('Karasu', 54),
('Kaynarca', 54),
('Pamukova', 54),
('Sapanca', 54),

-- Samsun
('Samsun Merkez', 55),
('Alaçam', 55),
('Asarcık', 55),
('Atakum', 55),
('Ayvacık', 55),
('Bafra', 55),
('Canik', 55),
('Çarşamba', 55),
('Havza', 55),
('İlkadım', 55),
('Kavak', 55),
('Ladik', 55),
('Salıpazarı', 55),
('Tekkeköy', 55),
('Terme', 55),
('Vezirköprü', 55),
('Yakakent', 55),

-- Siirt
('Siirt Merkez', 56),
('Baykan', 56),
('Eruh', 56),
('Kurtalan', 56),
('Pervari', 56),
('Şirvan', 56),

-- Sinop
('Sinop Merkez', 57),
('Ayancık', 57),
('Boyabat', 57),
('Dikmen', 57),
('Durağan', 57),
('Erfelek', 57),
('Gerze', 57),
('Saraydüzü', 57),
('Türkeli', 57),

-- Sivas
('Sivas Merkez', 58),
('Akıncılar', 58),
('Altınyayla', 58),
('Divriği', 58),
('Doğanşar', 58),
('Gemerek', 58),
('Gölova', 58),
('Gürün', 58),
('Hafik', 58),
('İmranlı', 58),
('Kangal', 58),
('Koyulhisar', 58),
('Suşehri', 58),
('Şarkışla', 58),
('Ulaş', 58),
('Yıldızeli', 58),
('Zara', 58),

-- Tekirdağ
('Tekirdağ Merkez', 59),
('Çorlu', 59),
('Çerkezköy', 59),
('Ergene', 59),
('Marmara Ereğlisi', 59),
('Malkara', 59),
('Saray', 59),
('Kapaklı', 59),
('Hayrabolu', 59),
('Şarköy', 59),

-- Tokat
('Tokat Merkez', 60),
('Artova', 60),
('Başçiftlik', 60),
('Erbaa', 60),
('Niksar', 60),
('Reşadiye', 60),
('Turhal', 60),
('Zile', 60),
('Pazar', 60),
('Yeşilyurt', 60),

-- Trabzon
('Trabzon Merkez', 61),
('Akçaabat', 61),
('Araklı', 61),
('Arsin', 61),
('Beşikdüzü', 61),
('Çarşıbaşı', 61),
('Çaykara', 61),
('Dernekpazarı', 61),
('Düzköy', 61),
('Hayrat', 61),
('Köprübaşı', 61),
('Maçka', 61),
('Of', 61),
('Sürmene', 61),
('Şalpazarı', 61),
('Tonya', 61),
('Vakfıkebir', 61),
('Yomra', 61),

-- Tunceli
('Tunceli Merkez', 62),
('Çemişgezek', 62),
('Hozat', 62),
('Mazgirt', 62),
('Nazımiye', 62),
('Ovacık', 62),
('Pertek', 62),

-- Şanlıurfa
('Şanlıurfa Merkez', 63),
('Akçakale', 63),
('Birecik', 63),
('Bozova', 63),
('Ceylanpınar', 63),
('Eyyübiye', 63),
('Halfeti', 63),
('Haliliye', 63),
('Hilvan', 63),
('Siverek', 63),
('Suruç', 63),
('Viranşehir', 63),

-- Uşak
('Uşak Merkez', 64),
('Banaz', 64),
('Eşme', 64),
('Karahallı', 64),
('Sivaslı', 64),

-- Van
('Van Merkez', 65),
('Bahçesaray', 65),
('Başkale', 65),
('Çaldıran', 65),
('Çatak', 65),
('Edremit', 65),
('Erciş', 65),
('Gevaş', 65),
('Gürpınar', 65),
('İpekyolu', 65),
('Muradiye', 65),
('Özalp', 65),

-- Yozgat
('Yozgat Merkez', 66),
('Akdağmadeni', 66),
('Boğazlıyan', 66),
('Çekerek', 66),
('Sorgun', 66),
('Yerköy', 66),
('Sarıkaya', 66),
('Aydıncık', 66),
('Kadışehri', 66),
('Saraykent', 66),
('Çayıralan', 66),

-- Zonguldak
('Zonguldak Merkez', 67),
('Alaplı', 67),
('Çaycuma', 67),
('Devrek', 67),
('Gökçebey', 67),
('Kilimli', 67),

-- Aksaray
('Aksaray Merkez', 68),
('Ağaçören', 68),
('Eskil', 68),
('Gülağaç', 68),
('Güzelyurt', 68),
('Ortaköy', 68),
('Sarıyahşi', 68),

-- Bayburt
('Bayburt Merkez', 69),
('Aydıntepe', 69),
('Demirözü', 69),

-- Karaman
('Karaman Merkez', 70),
('Ayrancı', 70),
('Başyayla', 70),
('Ermenek', 70),
('Kazımkarabekir', 70),
('Sarıveliler', 70),

-- Kırıkkale
('Kırıkkale Merkez', 71),
('Bahşili', 71),
('Balışeyh', 71),
('Çelebi', 71),
('Delice', 71),
('Karakeçili', 71),
('Keskin', 71),
('Sulakyurt', 71),
('Yahşihan', 71),

-- Batman
('Batman Merkez', 72),
('Beşiri', 72),
('Gercüş', 72),
('Hasankeyf', 72),
('Kozluk', 72),
('Sason', 72),

-- Şırnak
('Şırnak Merkez', 73),
('Beytüşşebap', 73),
('Cizre', 73),
('Güçlükonak', 73),
('İdil', 73),
('Silopi', 73),
('Uludere', 73),

-- Bartın
('Bartın Merkez', 74),
('Amasra', 74),
('Kurucaşile', 74),
('Ulus', 74),
('İnkaya', 74),
('Gömük', 74),
('Düzce', 74),

-- Ardahan
('Ardahan Merkez', 75),
('Çıldır', 75),
('Damal', 75),
('Göle', 75),

-- Iğdır
('Iğdır Merkez', 76),
('Aralık', 76),
('Karakoyunlu', 76),
('Tuzluca', 76),

-- Yalova
('Yalova Merkez', 77),
('Altınova', 77),
('Armutlu', 77),
('Çınarcık', 77),
('Çiftlikköy', 77),
('Termal', 77),

-- Karabük
('Karabük Merkez', 78),
('Eflani', 78),
('Eskipazar', 78),
('Ovacık', 78),
('Safranbolu', 78),
('Yenice', 78),

-- Kilis
('Kilis Merkez', 79),
('Elbeyli', 79),
('Polateli', 79),
('Musabeyli', 79),
('Yavuzlu', 79),

-- Osmaniye
('Osmaniye Merkez', 80),
('Bahçe', 80),
('Düziçi', 80),
('Hasanbeyli', 80),
('Kadirli', 80),
('Sumbas', 80),

-- Düzce
('Düzce Merkez', 81),
('Akçakoca', 81),
('Cumayeri', 81),
('Çilimli', 81),
('Gölyaka', 81),
('Gümüşova', 81),
('Kaynaşlı', 81),
('Yığılca', 81);

